# Generated by Django 4.0.2 on 2022-03-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_busdetail_timing_busdetail_dest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='booked_by_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
